import {
  IconAlertTriangle,
  IconArrowRight,
  IconBrandGithub,
  IconBrandTwitter,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDice2,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconSettings,
  IconShoppingBag,
  IconSphere,
  IconSteam,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserCode,
  IconUserEdit,
  IconUserX,
  IconX
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  dice2: IconDice2,
  userCode: IconUserCode,
  sphere: IconSphere,
  steam: IconSteam
};
