spring:
  application:
    name: game-catalog
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost/postgres
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: localhost

springdoc:
  enable-default-api-docs: false