spring:
  application:
    name: game-library
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost/postgres
    user: postgres
    password: postgres